import type { GraphState } from "@/lib/types/graph";

export const mockGraph: GraphState = {
  selectedNodeId: "feature-waitlist-signup",
  timeline: [],
  features: [
    {
      id: "feature-launch-page",
      name: "Launch Page",
      description: "A Next.js landing page that explains the product and drives signup.",
      source: "prd",
      status: "not_started",
      confidence: 0.9,
      acceptanceCriteria: [
        {
          id: "ac-launch-value",
          text: "Visitors can understand the product value on the landing page.",
          status: "unknown",
          evidenceIds: ["evidence-launch-page-prd"],
        },
      ],
      artifacts: [
        {
          id: "artifact-home-page",
          path: "app/page.tsx",
          kind: "ui",
          role: "Landing page",
          confidence: 0.9,
          evidence: "Primary Next.js route for the launch experience.",
        },
        {
          id: "artifact-hero-section",
          path: "components/marketing/HeroSection.tsx",
          kind: "ui",
          role: "Value proposition",
          confidence: 0.78,
          evidence: "Marketing component that carries the product message.",
        },
      ],
      evidence: [
        {
          id: "evidence-launch-page-prd",
          type: "prd",
          title: "PRD source",
          detail: "Landing page should make the product value clear.",
          confidence: 0.9,
        },
      ],
    },
    {
      id: "feature-waitlist-signup",
      name: "Waitlist Signup",
      description: "Visitors can submit an email and role through a validated signup flow.",
      source: "prd",
      status: "not_started",
      confidence: 0.94,
      riskSummary: "Signup needs API, persistence, and passing test evidence.",
      acceptanceCriteria: [
        {
          id: "ac-email-role",
          text: "Visitors can join the waitlist with an email address and role.",
          status: "missing_evidence",
          evidenceIds: ["evidence-waitlist-signup-prd"],
        },
        {
          id: "ac-duplicate-email",
          text: "Duplicate emails are handled with a friendly message.",
          status: "missing_evidence",
          evidenceIds: ["evidence-waitlist-signup-prd"],
        },
        {
          id: "ac-leads-saved",
          text: "Leads are saved for follow-up by the team.",
          status: "missing_evidence",
          evidenceIds: ["evidence-waitlist-signup-prd"],
        },
        {
          id: "ac-signup-tests",
          text: "There are tests for valid signup, duplicate signup, and invalid email.",
          status: "missing_evidence",
          evidenceIds: ["evidence-waitlist-signup-prd"],
        },
      ],
      artifacts: [
        {
          id: "artifact-waitlist-form",
          path: "components/waitlist/SignupForm.tsx",
          kind: "ui",
          role: "Signup form",
          confidence: 0.86,
          evidence: "Customer-facing form for email and role capture.",
        },
        {
          id: "artifact-waitlist-api",
          path: "app/api/waitlist/route.ts",
          kind: "api",
          role: "Signup endpoint",
          confidence: 0.92,
          evidence: "Route handler receives signup submissions.",
        },
        {
          id: "artifact-waitlist-store",
          path: "lib/waitlist/store.ts",
          kind: "service",
          role: "Lead persistence",
          confidence: 0.82,
          evidence: "Server-side helper stores and de-duplicates leads.",
        },
        {
          id: "artifact-waitlist-schema",
          path: "prisma/schema.prisma",
          kind: "db",
          role: "Lead model",
          confidence: 0.76,
          evidence: "Persistence schema for waitlist leads.",
        },
        {
          id: "artifact-waitlist-test",
          path: "tests/waitlist-signup.test.ts",
          kind: "test",
          role: "Signup coverage",
          confidence: 0.88,
          evidence: "Tests validate signup, duplicates, and invalid email.",
        },
      ],
      evidence: [
        {
          id: "evidence-waitlist-signup-prd",
          type: "prd",
          title: "PRD source",
          detail: "Waitlist flow includes UI, API, persistence, duplicate handling, and tests.",
          confidence: 0.94,
        },
      ],
    },
    {
      id: "feature-admin-leads",
      name: "Lead Review",
      description: "Product managers can inspect the latest waitlist leads without reading code.",
      source: "prd",
      status: "not_started",
      confidence: 0.84,
      acceptanceCriteria: [
        {
          id: "ac-admin-review",
          text: "Product managers can review recent leads in an admin view.",
          status: "unknown",
          evidenceIds: ["evidence-admin-leads-prd"],
        },
      ],
      artifacts: [
        {
          id: "artifact-admin-leads-page",
          path: "app/admin/leads/page.tsx",
          kind: "ui",
          role: "Lead review screen",
          confidence: 0.82,
          evidence: "Admin route lists recent waitlist leads.",
        },
        {
          id: "artifact-admin-leads-table",
          path: "components/admin/LeadTable.tsx",
          kind: "ui",
          role: "Lead table",
          confidence: 0.78,
          evidence: "Table component presents captured leads for PM review.",
        },
      ],
      evidence: [
        {
          id: "evidence-admin-leads-prd",
          type: "prd",
          title: "PRD source",
          detail: "Admin review supports product managers after launch.",
          confidence: 0.84,
        },
      ],
    },
  ],
  edges: [
    {
      id: "edge-launch-waitlist",
      from: "feature-launch-page",
      to: "feature-waitlist-signup",
      type: "depends_on",
      confidence: 0.82,
      evidenceIds: ["evidence-launch-page-prd", "evidence-waitlist-signup-prd"],
    },
    {
      id: "edge-waitlist-admin",
      from: "feature-waitlist-signup",
      to: "feature-admin-leads",
      type: "depends_on",
      confidence: 0.78,
      evidenceIds: ["evidence-waitlist-signup-prd", "evidence-admin-leads-prd"],
    },
  ],
};
