import type { CodexTimelineEvent } from "@/lib/types/codex";

const baseTime = "2026-04-29T01:00:00.000Z";

export const mockCodexEvents: CodexTimelineEvent[] = [
  {
    id: "event-plan-1",
    type: "plan_updated",
    title: "Plan: build full-stack Next.js waitlist",
    detail:
      "Connect the landing page, signup form, route handler, persistence helper, admin review, and tests.",
    timestamp: baseTime,
    featureIds: [
      "feature-launch-page",
      "feature-waitlist-signup",
      "feature-admin-leads",
    ],
  },
  {
    id: "event-file-landing",
    type: "file_change",
    title: "Built app/page.tsx",
    detail: "Added launch copy, audience framing, and a clear waitlist call to action.",
    timestamp: baseTime,
    paths: ["app/page.tsx", "components/marketing/HeroSection.tsx"],
    featureIds: ["feature-launch-page"],
  },
  {
    id: "event-file-form",
    type: "file_change",
    title: "Added waitlist signup form",
    detail: "Captured email and role with inline loading, success, and duplicate states.",
    timestamp: baseTime,
    paths: ["components/waitlist/SignupForm.tsx"],
    featureIds: ["feature-waitlist-signup"],
  },
  {
    id: "event-file-api",
    type: "file_change",
    title: "Added signup API and persistence",
    detail:
      "Created the Next.js route handler, lead store helper, and Lead database model.",
    timestamp: baseTime,
    paths: [
      "app/api/waitlist/route.ts",
      "lib/waitlist/store.ts",
      "prisma/schema.prisma",
    ],
    featureIds: ["feature-waitlist-signup"],
  },
  {
    id: "event-command-1",
    type: "command_started",
    title: "Running waitlist tests",
    timestamp: baseTime,
    command: "npm test -- waitlist-signup",
    featureIds: ["feature-waitlist-signup"],
  },
  {
    id: "event-test-failed",
    type: "command_completed",
    title: "Waitlist tests failed",
    detail: "Duplicate signup returned a raw conflict instead of a friendly message.",
    timestamp: baseTime,
    command: "npm test -- waitlist-signup",
    exitCode: 1,
    featureIds: ["feature-waitlist-signup"],
  },
  {
    id: "event-file-duplicate-fix",
    type: "file_change",
    title: "Patched duplicate signup handling",
    detail: "Returned a reusable success state when an email already exists.",
    timestamp: baseTime,
    paths: ["app/api/waitlist/route.ts", "lib/waitlist/store.ts"],
    featureIds: ["feature-waitlist-signup"],
  },
  {
    id: "event-file-tests",
    type: "file_change",
    title: "Added full-stack signup tests",
    detail: "Covered valid signup, duplicate signup, and invalid email validation.",
    timestamp: baseTime,
    paths: ["tests/waitlist-signup.test.ts"],
    featureIds: ["feature-waitlist-signup"],
  },
  {
    id: "event-command-2",
    type: "command_completed",
    title: "Waitlist tests passed",
    detail: "The Next.js signup route now passes valid, duplicate, and invalid email cases.",
    timestamp: baseTime,
    command: "npm test -- waitlist-signup",
    exitCode: 0,
    featureIds: ["feature-waitlist-signup"],
  },
  {
    id: "event-file-admin",
    type: "file_change",
    title: "Added admin lead review",
    detail: "Created a simple PM-facing page for recent leads and signup context.",
    timestamp: baseTime,
    paths: ["app/admin/leads/page.tsx", "components/admin/LeadTable.tsx"],
    featureIds: ["feature-admin-leads"],
  },
  {
    id: "event-command-fullstack",
    type: "command_completed",
    title: "Full-stack checks passed",
    detail: "Next.js build and waitlist tests passed after landing page, API, persistence, and admin review changes.",
    timestamp: baseTime,
    command: "npm run build && npm test -- waitlist-signup",
    exitCode: 0,
    featureIds: [
      "feature-launch-page",
      "feature-waitlist-signup",
      "feature-admin-leads",
    ],
  },
  {
    id: "event-drift-1",
    type: "file_change",
    title: "Unexpected edit: next.config.ts",
    detail: "No PRD feature or current launch task maps to build configuration changes.",
    timestamp: baseTime,
    paths: ["next.config.ts"],
  },
];
